force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Reject_Count__c.field-meta.xml
<CustomField>
    <fullName>Reject_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reject Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Timesheet_Status__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_Status__c</fullName>
    <label>Timesheet Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/epic0/TimesheetUpdateFields.cls
public with sharing class TimesheetUpdateFields {
    public TimesheetUpdateFields() {

    }

    public static void updateRejectionCount(List<Timesheet__c> updatedTimesheets, 
                                            Map<Id, Timesheet__c> oldTimesheetValues) {
        for(Timesheet__c t : updatedTimesheets) {
            if(t.Timesheet_Status__c == 'Rejected'
                 && oldTimesheetValues.get(t.Id).Timesheet_Status__c != 'Rejected') {
                    if(t.Number_of_Times_Rejected__c == null) {
                        t.Number_of_Times_Rejected__c = 0;
                    }
                t.Reject_Count__c = t.Reject_Count__c + 1;
            }
        }
    }

    public static void updateProgramManager(List<Timesheet__c> newTimesheets) {
        List<Id> projectIds = new List<Id>();
        Map<Id,Timesheet__c> timesheetMap = new Map<Id,Timesheet__c>();
        for(Timesheet__c t : newTimesheets) {    
            if(t.Project__c != null) {
                projectIds.add(t.Project__c);
                timesheetMap.put(t.Project__c,t);
            }    
        }

        List<Project__c> queriedProjects = [ SELECT OwnerId 
                                                FROM Project__c
                                                WHERE Id IN :projectIds];

        for(Project__c project : queriedProjects) {
            if(timesheetMap.containsKey(project.Id)) {
                timesheetMap.get(project.Id).Project_Manager__c = project.OwnerId;
            }
        }                                    
    }

    public static void closeRelatedTasks(List<Timesheet__c> updatedTimesheets) {
        List<Id> finalizedTimecardIds = new List<Id>();
        for(Timesheet__c t : updatedTimesheets) {
            if(t.Timesheet_Status__c == 'Submitted'){
                finalizedTimecardIds.add(t.id);
            }
        }

        List<Task> relatedTasks = [ SELECT Status 
                                        FROM Task 
                                        WHERE WhatId IN :finalizedTimecardIds ];

        for(Task t : relatedTasks) {
            t.Status = 'Completed';
        }

        update relatedTasks;
    }
}