force-app/main/default/objects/Timesheet__c/Timesheet__c.object-meta.xml
<CustomObject>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Timesheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Timesheet__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Timesheets</relationshipLabel>
    <relationshipName>Timesheets</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Timesheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Reject_Count__c.field-meta.xml
<CustomField>
    <fullName>Reject_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reject Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Timesheet__c/fields/Timesheet_Status__c.field-meta.xml
<CustomField>
    <fullName>Timesheet_Status__c</fullName>
    <label>Timesheet Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/epic0/TimesheetUpdateFiledsTest.cls
@isTest
private class TimesheetUpdateFiledsTest {

    @isTest
    static void updateRejectionCount_givenRejectedTimecard_shouldIncrement(){
        Project__c testProject = new Project__c();
        testProject.Name = 'Unit Test Project';
        insert testProject;
        
        Timesheet__c testTimesheet = new Timesheet__c();
        testTimesheet.Project__c = testProject.Id;
        testTimesheet.Timesheet_Status__c = 'Draft';
        testTimesheet.Employee__c = '0037c000015eFmHAAU';
        insert testTimesheet;

        Test.startTest();

        testTimesheet.Timesheet_Status__c = 'Rejected';
        update testTimesheet;

        Test.stopTest();

        List<Timesheet__c> updatedTimesheets = [ SELECT Reject_Count__c FROM Timesheet__c ];
        System.assertEquals(1, updatedTimesheets[0].Reject_Count__c, 
                                'Rejection Number should have been incremented');
    }

    @isTest
    static void updateRejectionCount_givenSubmittedTimecard_shouldNotIncrement(){
        Project__c testProject = new Project__c();
        testProject.Name = 'Unit Test Project';
        insert testProject;
        
        Timesheet__c testTimesheet = new Timesheet__c();
        testTimesheet.Project__c = testProject.Id;
        testTimesheet.Timesheet_Status__c = 'Draft';
        testTimesheet.Employee__c = '0037c000015eFmHAAU';
        insert testTimesheet;

        Test.startTest();

        testTimesheet.Timesheet_Status__c = 'Submitted';
        update testTimesheet;

        Test.stopTest();

        List<Timesheet__c> updatedTimesheets = [ SELECT Reject_Count__c FROM Timesheet__c ];
        System.assertEquals(0, updatedTimesheets[0].Reject_Count__c, 
                                'Rejection Number should not have been incremented');
    }

    @isTest
    static void updateRejectionCount_givenAlreadyRejectedTimecard_shouldNotIncrementAgain(){
        Project__c testProject = new Project__c();
        testProject.Name = 'Unit Test Project';
        insert testProject;
        
        Timesheet__c testTimesheet = new Timesheet__c();
        testTimesheet.Project__c = testProject.Id;
        testTimesheet.Timesheet_Status__c = 'Draft';
        testTimesheet.Employee__c = '0037c000015eFmHAAU';
        insert testTimesheet;

        testTimesheet.Timesheet_Status__c = 'Rejected';
        update testTimesheet;

        Test.startTest();
        
        update testTimesheet;

        Test.stopTest();

        List<Timesheet__c> updatedTimesheets = [ SELECT Reject_Count__c FROM Timesheet__c ];
        System.assertEquals(1, updatedTimesheets[0].Reject_Count__c, 
                                'Rejection Number should not have been incremented more than once');
    }

    @isTest
    static void updateProgramManager_givenNewlyCreatedTimesheet_shouldUpdateProjectManager(){
        Project__c testProject = new Project__c();
        testProject.Name = 'Unit Test Project';
        insert testProject;
        
        Timesheet__c testTimesheet = new Timesheet__c();
        testTimesheet.Project__c = testProject.Id;
        testTimesheet.Timesheet_Status__c = 'Draft';
        testTimesheet.Employee__c = UserInfo.getUserId();

        Test.startTest();      
        insert testTimesheet;
        Test.stopTest();

        List<Timesheet__c> updatedTimesheets = [ SELECT Project_Manager__c FROM Timesheet__c ];
        System.assertNotEquals(null, updatedTimesheets[0].Project_Manager__c, 
                                'Project Manager is not null');
    }
}